org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

android.useAndroidX=true
android.enableJetifier=true

org.gradle.parallel=false
org.gradle.configureondemand=true

kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false