// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcpDY2rbM00JHrL-CGaXQQl-bmvInLNbA',
    appId: '1:376797794992:web:7e95f4fa010e32c1d82175',
    messagingSenderId: '376797794992',
    projectId: 'hash-ee6fc',
    authDomain: 'hash-ee6fc.firebaseapp.com',
    storageBucket: 'hash-ee6fc.appspot.com',
    measurementId: 'G-39QZ23274G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Xb7IoP_JZfF0KEPMouS7dmVg1CiIxyQ',
    appId: '1:376797794992:android:5bd85a3cefcc0db7d82175',
    messagingSenderId: '376797794992',
    projectId: 'hash-ee6fc',
    storageBucket: 'hash-ee6fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXO-uoxj4l3avsid_N5rxUDRbSPK0z2B0',
    appId: '1:376797794992:ios:aa916bac09884b8ed82175',
    messagingSenderId: '376797794992',
    projectId: 'hash-ee6fc',
    storageBucket: 'hash-ee6fc.firebasestorage.app',
    androidClientId: '376797794992-6n1pa1g8kmo87g98mknh7nlbj6br177f.apps.googleusercontent.com',
    iosClientId: '376797794992-ikpq7h5o7flrhgmm53otlf1sm973489h.apps.googleusercontent.com',
    iosBundleId: 'com.hfg.hash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXO-uoxj4l3avsid_N5rxUDRbSPK0z2B0',
    appId: '1:376797794992:ios:08f6d3bd447c1ebfd82175',
    messagingSenderId: '376797794992',
    projectId: 'hash-ee6fc',
    storageBucket: 'hash-ee6fc.appspot.com',
    iosBundleId: 'com.example.hash.RunnerTests',
  );
}